version: "3.9"
services:
  data-collector:
    build:
      context: .
      args:
        - OCTOPUS_ENERGY_API_KEY
        - ELECTRICITY_METER_MPAN
        - ELECTRICITY_METER_SERIAL_NUMBER
        - INFLUXDB_USERNAME
        - INFLUXDB_PASSWORD
        - INFLUXDB_TOKEN
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:2.1.1
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: energy
      DOCKER_INFLUXDB_INIT_BUCKET: consumption
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
    ports:
      - "8086:8086"

  grafana:
    image: grafana/grafana
    # Pass through environment variables from host machine to docker container (as they are used in the provisioned datasources/dashboards)
    environment:
      INFLUXDB_USERNAME:
      INFLUXDB_PASSWORD:
      INFLUXDB_TOKEN:
    ports:
      - "3001:3000"
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb