version: "3.9"
services:
  influxdb:
    image: influxdb:2.1.1
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: energy
      DOCKER_INFLUXDB_INIT_BUCKET: consumption
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
    ports:
      - "8086:8086"

  # NOTE - when setting up the datasource you need to use 'http://influxdb:8086' as the URL
  grafana:
    image: grafana/grafana
    # Pass through environment variables from host machine to docker container (as they are used in the provisioned datasources)
    environment:
      INFLUXDB_USERNAME:
      INFLUXDB_PASSWORD:
      INFLUXDB_TOKEN:
    ports:
      - "3001:3000"
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb